# Step 1: 기본 이미지를 선택합니다. Boost 및 빌드 도구 설치를 위해 Ubuntu 이미지를 사용합니다.
FROM ubuntu:22.04

# Step 2: 필수 패키지를 설치합니다.
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    libboost-all-dev \
    && apt-get clean

# Step 3: 작업 디렉토리를 설정합니다.
WORKDIR /Users/seong-ikje/Desktop/sys_lan_pratice/mobis_performance_test_code/

# Step 4: 로컬에 있는 UDP 클라이언트 소스 파일과 CMakeLists.txt 파일을 컨테이너로 복사합니다.
COPY . .

# Step 5: CMake를 사용하여 UDP 클라이언트를 빌드합니다.
RUN mkdir build && cd build && cmake .. && make

# Step 6: 클라이언트를 실행합니다. 
# 실제로 이미지를 실행할 때 추가 인자를 넣어 실행할 수 있도록 ENTRYPOINT를 사용합니다.
ENTRYPOINT ["./build/client"]

